config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'projects', to: 'pages#projects'
  get 'contact', to: 'pages#contact'
  get 'github', to: 'pages#github'
  get 'blog', to: 'pages#blog'
  get 'resume', to: 'pages#resume'
  get 'demos', to: 'pages#demos'
  get 'lp', to: 'pages#lp'
  resources :articles do
    resources :commments
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    @article.save
      if @article.save
        redirect_to @article
      else
        render 'index'
      end
    end

    def update
      @article = Article.find(params[:id])

      if @article.update(article_params)
        redirect_to @article
      else
        render 'edit'
      end
    end

    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def github
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def resume
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= form_for :article, url: article_path(@article), method: :patch do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<!-- Intro and header -->
  <div id="blog" class="inner-content">

      <section id="page-title" class="inner-section">
        <div class="container-fluid nopadding wow fadeInRight" data-wow-delay="0.4s" data-wow-offset="10">
            <h2 class="font-accident-two-normal uppercase">COMING SOON</h2>
            <h5 class="font-accident-one-bold hovercolor uppercase">Curated design-content for the suave developer.</h5>
        </div>

      <!-- Blog Image Placeholder -->
        <div class="timeline-panel wow fadeInLeft" data-wow-delay="0.3s" data-wow-offset="10">
          <table>
            <tr>
              <th>Title</th>
              <th>Text</th>
            </tr>

            <% @articles.each do |article| %>
              <tr>
                <td><%= article.title %></td>
                <td><%= article.text %></td>
                <td><%= link_to 'Show', article_path(article) %></td>
              </tr>
            <% end %>
          </table>
        </div>

      </section>
  </div>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Deven Blackburn | Developer | ReactJS, HTML5, CSS3, JavaScript</title>
        <meta name="description" content="Developer, proficient in HTML, CSS and JavaScript. Skilled at Frontend and Backend web development." />
        <meta name="keywords" content="HTML, CSS, JavaScript, HTML5, CSS3, JS, jQuery, React, ReactJS, Web Design, Development, Frontend" />
        <meta name="author" content="Deven Blackburn" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name=viewport content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" sizes="76x76" href="apple-touch-icon-76x76.png">
        <link rel="icon" type="image/png" href="favicon-96x96.png" sizes="96x96">
        <link rel="manifest" href="manifest.json">
        <%= csrf_meta_tags %>

        <!-- Facebook -->
        <meta property="og:title" content="Deven Blackburn | Developer">
        <meta property="og:description" content="Developer, proficient in HTML, CSS and JavaScript. Skilled at Frontend and Backend web development.">
        <meta property="og:image" content="https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/resume-headshot.png">

        <!-- Twitter -->
        <meta name="twitter:card" content="summary">
        <meta name="twitter:site" content="@makecodenotwar">
        <meta name="twitter:creator" content="@makecodenotwar">
        <meta name="twitter:url" content="http://www.makecodenotwar.co">
        <meta name="twitter:title" content="Deven Blackburn | Developer">
        <meta name="twitter:description" content="Developer, proficient in HTML, CSS and JavaScript. Skilled at Frontend and Backend web development.">
        <meta name="twitter:image" content="https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/resume-headshot.png">

        <!-- Stylesheets-->
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

        <!-- Javascript -->
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-115313291-1"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'UA-115313291-1');
        </script>
        <meta name="google-site-verification" content="B4vvi2BJlsL23enG29_tyG7-m2p0RtaRUraxKGikdBQ" />

    </head>

    <body class="boxed nopadding">
    <header>
       <section id="top-navigation" class="container-fluid nopadding">
          <div class="row nopadding ident dark-fish-skin-texture">

            <!-- Main Photo -->
            <a href="<%= root_path %>">
              <div class="col-md-5 col-lg-4 vc-photo"></div>
            </a>

        <div class="col-md-7 col-lg-8 vc-name nopadding">

          <!-- Name positioning -->
            <div class="row nopadding name">
              <div class="col-md-10 name-title">
                <h2 class="font-accident-two-light uppercase">Deven Blackburn</h2>
              </div>
            </div>

          <!-- Description positioning -->
            <div class="row nopadding position">
              <div class="col-md-10 position-title">
                <section class="cd-intro">
                  <h4 class="cd-headline clip is-full-width font-accident-two-normal uppercase">
                    <span>passionate </span>
                    <span class="cd-words-wrapper">
                      <b class="is-visible">Front End Developer</b>
                      <b>Oenophile</b>
                      <b>Product Manager</b>
                      <b>Armchair Archaeologist</b>
                      <b>Full Stack Developer</b>
                      <b>& Well-Rounded</b>
                    </span>
                  </h4>
                </section>
              </div>
            </div>

          <!-- Main Navigation -->
            <ul class="row nopadding cd-side-navigation">
              <li class="col-xs-4 col-sm-2 nopadding menuitem eggplant">
                <a href="<%= root_path %>" class="hvr-sweep-to-bottom"><br>
                  <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-home.png", :size => '54x54' %>
                  <span>home</span>
                </a>
              </li>
              <li class="col-xs-4 col-sm-2 nopadding menuitem misted-guava">
                <a href="<%= resume_path %>" class="hvr-sweep-to-bottom"><br>
                  <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-resume2.png", :size => '54x54' %>
                  <span>resume</span>
                </a>
              </li>
              <li class="col-xs-4 col-sm-2 nopadding menuitem dusted-lemon">
                <a href="<%= projects_path %>" class="hvr-sweep-to-bottom"><br>
                  <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-projects3.png", :size => '54x54' %>
                  <span>projects</span>
                </a>
              </li>
              <li class="col-xs-4 col-sm-2 nopadding menuitem aqua">
                <a href="<%= contact_path %>" class="hvr-sweep-to-bottom"><br>
                  <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-contact.png", :size => '54x54' %>
                  <span>contact</span>
                </a>
              </li>
              <li class="col-xs-4 col-sm-2 nopadding menuitem succulent">
                <a href="<%= blog_path %>" class="hvr-sweep-to-bottom"><br>
                  <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-blog.png", :size => '54x54' %>
                  <span>blog</span>
                </a>
              </li>
              <li class="col-xs-4 col-sm-2 nopadding menuitem seaweed github">
                <a href="<%= github_path %>" class="hvr-sweep-to-bottom"><br>
                  <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-github.png", :size => '54x54' %>
                  <span>github</span>
                </a>
              </li>
            </ul>

          </div>

        </div>
      </section>
    </header>

      <!-- Page Content Container -->
        <div class="content-wrap">
           <section id="homesection" class="container-fluid nopadding">
              <div class="m-details row nopadding">

                  <%= yield %>

              </div>
           </section>
        </div>

      <!--Footer-->
        <footer id="footer" class="padding-50 dark-fish-skin-texture">
               <div class="container-fluid nopadding">
                  <div class="row wow fadeInUp" data-wow-delay=".2s" data-wow-offset="40" data-wow-duration="2s">

                  <!-- Name and call to action -->
                    <div class="col-md-3">
                      <h4 class="font-accident-two-bold uppercase">Deven Blackburn</h4>
                      <p class="inline-block">Your full service, full stack<br>
                        Developer.  <i>How can I help?</i></p>
                      <div class="divider-dynamic"></div>
                    </div>

                  <!-- Resume download -->
                    <div class="col-md-3 cv-link">
                      <h4 class="font-accident-two-bold uppercase">Download My Resume</h4>
                          <a href="https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/Deven_Blackburn_CV.pdf" target="blank_">
                            <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/download.png", :size => '13x13' %>
                            English
                          </a>
                          <a href="https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/Deven_Blackburn_CV.pdf" target="blank_">
                            <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/download.png", :size => '13x13' %>
                            Spanish
                          </a>
                        <div class="divider-dynamic"></div>
                    </div>

                  <!-- Social links -->
                    <div class="col-md-3">
                      <h4 class="font-accident-two-bold uppercase">Follow me at</h4>
                        <div class="inline-block">
                          <a href="https://www.facebook.com/makecodenotwar" target="_blank">
                            <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/social-facebook.png" %>
                          </a>
                        </div>
                        <div class="inline-block">
                          <a href="https://twitter.com/MakeCodeNotWar" target="_blank">
                            <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/social-twitter.png" %>
                          </a>
                        </div>
                        <div class="inline-block">
                          <a href="https://www.instagram.com/makecodenotwar/" target="_blank">
                            <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/social-instagram.png" %>
                          </a>
                        </div>
                        <div class="inline-block">
                          <a href="https://www.linkedin.com/in/devenblackburn" target="_blank">
                            <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/social-linkedin.png" %>
                          </a>
                        </div>
                        <div class="inline-block">
                          <a href="https://github.com/hkdeven" target="_blank">
                            <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/social-github.png" %>
                          </a>
                        </div>
                        <div class="divider-dynamic"></div>
                     </div>

                     <!-- Handmade -->
                       <div class="col-md-2">
                         <h4 class="font-accident-two-bold uppercase">#madeinFLL</h4>
                         <p class="inline-block">
                           <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-coded-left.png", :size => '15x15', alt: "Coded" %><%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-coded-right.png", :size => '15x15', alt: "Coded" %>
                           with
                           <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-heart.png", :size => '15x15', alt: "Love" %>
                           <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-coffee.png", :size => '18x18', alt: "LOTS of coffee" %>
                           <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-wine.png", :size => '15x15', alt: "Wine" %>
                         </p>
                         <div class="divider-dynamic"></div>
                       </div>

                  </div>
                </div>

              </div>
        </footer>

        <div id="image-cache" class="hidden"></div>

  </body>
</html>

app/views/pages/github.html.erb
<!-- Intro and header -->
  <div id="blog" class="inner-content">

      <section id="page-title" class="inner-section">
        <div class="container-fluid nopadding wow fadeInRight" data-wow-delay="0.4s" data-wow-offset="10">
            <h2 class="font-accident-two-normal uppercase">GITHUB</h2>
            <h5 class="font-accident-one-bold hovercolor uppercase">open source contributions and creations</h5>

      <div class="row">

        <!-- Github heatmap -->
          <div class="e-centered wow fadeInDown" data-wow-delay="0.4s" data-wow-offset="10" data-wow-duration="3s">
              <img src="http://ghchart.rshah.org/2b747d/hkdeven" alt="Deven's activity chart on Github" />
                <div id="github-widget" data-user="hkdeven" data-display="pop_repos,contribution,calendar"></div>
          </div>

        <div class="dividewhite2"></div>

        <!-- Button to Github -->
          <div class="row nopadding wow fadeInLeft" data-wow-delay=".9s" data-wow-offset="10" data-wow-duration="3s">
                <div class="github-card" data-github="hkdeven" data-width="400" data-height="" data-theme="default"></div>
                <script src="//cdn.jsdelivr.net/github-cards/latest/widget.js"></script>

                <!-- <a href="https://github.com/hkdeven" target="_blank">
                 <button class="btn btn-lg btn-lgr-str">
                   <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-github-button.png", :size => '16x16' %>
                   GITHUB PAGE
                 </button>
               </a> -->

            </div>
          </div>

      <!-- Github widget -->
       <div class="col-md-2 col-lg-2">&nbsp;</div>
          <div class="col-md-8 col-lg-8 e-centered wow fadeInDown" data-wow-delay="0.6s" data-wow-offset="10">
            <div id="github-widget" data-user="hkdeven" data-display="pop_repos,contribution,calendar"></div>
          </div>
            <script src="https://gh-widget.oyanglul.us/index.js"></script>
      </div>

        <div class="dividewhite2"></div>

    </div>
  </section>
</div>

app/views/pages/google2ac5bbddc416ebc3.html.html.erb
google-site-verification: google2ac5bbddc416ebc3.html

app/views/pages/home.html.erb
<div class="col-md-8 nopadding skin">
   <div class="padding-50 wow fadeInDown" data-wow-delay="0.3s" data-wow-offset="10">
      <div class="row nopadding">
         <div class="col-md-12 nopadding">
            <h3 class="font-accident-two-normal uppercase">About me</h3>
            <div class="quote">
              <h5 class="font-accident-one-bold hovercolor uppercase">Front+Back End Developer  •  Oenologist  •  Traveller</h5>
              <div class="dividewhite1"></div>
              <p class="small">
              Developer at Allied Buildings by day, <a href="https://www.facebook.com/nerdnitefll" target="_blank" alt="Nerd Nite Fort Lauderdale" >Nerd Nite Fort Lauderdale</a> organizer and <a href="https://cardsagainsthumanity.com/" target="_blank" alt="Cards Against Humanity" style="color: #3fb0ac !important">CAD</a> enthusiast by night. Lover of code, community, and wine.  <strong>#madeinFLL  #FLLtech  #nerdniteFLL</strong>
              </p>
            </div>
         </div>
      </div>
      <div class="divider-dynamic"></div>
      <div class="row nopadding">
         <div class="col-md-4 infoblock nopadding">
            <div class="row wow fadeInLeft" data-wow-delay="0.4s" data-wow-offset="10" data-wow-duration="2s">
              <div class="col-sm-1 col-md-3">
                <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-frameworks.png", :size => '44x44' %>
                <div class="dividewhite1"></div></div>
               <div class="col-sm-11 col-md-9 ">
                  <h5 class="font-accident-one-bold uppercase">Languages</h5>
                  <p class="small">
                     Ruby, Reactjs, HTML5, CSS3, SASS, Javascript, and JQuery. Database use includes PostgreSQL, sqlite, and SQL.
                  </p>
               </div>
            </div>
            <div class="divider-dynamic"></div>
         </div>
         <div class="col-md-4 infoblock nopadding">
           <div class="row wow fadeInLeft" data-wow-delay="0.6s" data-wow-offset="10" data-wow-duration="2.5s">
               <div class="col-sm-1 col-md-3 ">
                   <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-tools.png", :size => '44x44' %>
                 <div class="dividewhite1"></div></div>
               <div class="col-sm-11 col-md-9 ">
                  <h5 class="font-accident-one-bold uppercase">Frameworks</h5>
                  <p class="small">
                     Rails, Redux, Wordpress, Ember, Bootstrap, Bourbon, React, and MobX.
                  </p>
               </div>
            </div>
            <div class="divider-dynamic"></div>
         </div>
         <div class="col-md-4 infoblock nopadding">
           <div class="row wow fadeInLeft" data-wow-delay="0.8s" data-wow-duration="3s" data-wow-offset="10">
               <div class="col-sm-1 col-md-3">
                   <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/icon-pen.png", :size => '40x40' %>
                 <div class="dividewhite1"></div></div>
               <div class="col-sm-11 col-md-9">
                  <h5 class="font-accident-one-bold uppercase">Primary Tools</h5>
                  <p class="small">
                     Agile Methodologies, OOP, MVC, Git and GitHub, Google Apps Script (GAS), Heroku, Zoho CRM, Google Apps, AWS, Sketch, and a plethora of APIs.
                  </p>
               </div>
            </div>
            <div class="divider-dynamic"></div>
         </div>
      </div>
   </div>
</div>

<!-- Personal Information -->
<div class="col-md-4 personal nopadding">
   <div class="padding-50 wow fadeInRight" data-wow-delay="0.4s" data-wow-offset="10" data-wow-duration="4s">
     <div class="dividewhite3"></div>
      <h3 class="font-accident-two-normal uppercase font-color-invert">Personal Info</h3>
      <div class="dividewhite2"></div>
      <div>
         <div class="fullwidth box">
            <div class="one"><p class="small font-regular-bold uppercase font-color-invert">Name:</p></div>
            <div class="two"><p class="small font-color-invert">Deven Blackburn</p></div>
         </div>
         <div class="fullwidth box">
            <div class="one"><p class="small font-regular-bold uppercase font-color-invert">Address:</p></div>
            <div class="two"><p class="small font-color-invert">Fort Lauderdale, FL USA</p></div>
         </div>
         <div class="fullwidth box">
            <div class="one"><p class="small font-regular-bold uppercase font-color-invert">Phone:</p></div>
            <div class="two"><p class="small font-color-invert">+1.954.348.7293</p></div>
         </div>
         <div class="fullwidth box">
            <div class="one"><p class="small font-regular-bold uppercase font-color-invert">Email:</p></div>
            <div class="two"><p class="small font-color-invert">deven@makecodenotwar.co</p></div>
         </div>
         <div class="fullwidth box">
            <div class="one"><p class="small font-regular-bold uppercase font-color-invert">Github:</p></div>
            <div class="two"><p class="small font-color-invert">github.com/hkdeven</p></div>
         </div>
      </div>
   </div>
</div>

</div>

<div class="row nopadding">

<!-- Experience -->
<div class="col-md-4 pro-experience nopadding">
   <div class="padding-50 wow fadeInRight" data-wow-delay="0.6s" data-wow-offset="5" data-wow-duration="3.5s">
      <h3 class="font-accident-two-normal uppercase font-color-invert">Experience</h3>
      <div class="dividewhite2"></div>
      <div class="experience">
         <ul class="">
            <li class="company uppercase">
              <a href="<%= resume_path %>">Allied Buildings</a>
            </li>
            <li class="position">AUG 2016 - Present</li>
            <li class="position"><strong>Fullstack Developer</strong></li>
          </li>
          <li class="position">Responsible for website development, updates, and deployment. Assist with UI/UX design, site architecture, CRM workflow and automation, database reporting and logic, and various marketing campaigns. Heavy API usage across all products and internal workflows...</li>
          <a href="<%= resume_path %>">
          <%= image_tag "https://s3-us-west-2.amazonaws.com/fortlauderdaletech.org/portfolio/more.png", :size => '34x34'  %></a>
         </ul>
      </div>
   </div>
</div>

<!-- Learning Priorities -->
<div class="col-md-8 circle-skills nopadding seaweed">
   <div class="padding-50 wow fadeInLeft" data-wow-delay="0.6s" data-wow-offset="5">
      <h3 class="font-accident-two-normal uppercase font-color-invert">Never Stop Learning</h3>
      <div>
         <div class="fullwidth box">
            <div class="two"><p class="small font-color-invert">A developer never stops learning.  Here is my current reading list.</p></div>
         </div>
      <div class="row">
         <div class="col-sm-4 nopadding">
            <div class="progressbar" data-animate="false">
               <div class="circle font-accident-one-normal font-color-invert" data-percent="80">
                  <div></div>
                  <h4 class="font-accident-one-normal uppercase">Javascript</h4>
                  <p class="small">
                     ReactJS, Redux, Angular 1.X, and NodeJS
                  </p>
               </div>
            </div>
         </div>
         <div class="col-sm-4 nopadding">
            <div class="progressbar" data-animate="false">
               <div class="circle font-accident-one-normal font-color-invert" data-percent="10">
                  <div></div>
                  <h4 class="font-accident-one-normal uppercase">Front End & Design</h4>
                  <p class="small">
                     Sketch, InDesign, ReactJS
                  </p>
               </div>
            </div>
         </div>
         <div class="col-sm-4 nopadding">
            <div class="progressbar" data-animate="false">
               <div class="circle font-accident-one-normal font-color-invert" data-percent="10">
                  <div></div>
                  <h4 class="font-accident-one-normal uppercase">Reinforcement</h4>
                  <p class="small">
                     Ruby/Rails, JQuery, JS, Bootstrap
                  </p>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
</div>